-- pts_of-week set to NULL every week
USE quizz;
CREATE EVENT IF NOT EXISTS erase
ON SCHEDULE EVERY 1 WEEK
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 1 MONTH
DO
	UPDATE users SET pts_of_week = NULL;
